import { config } from "dotenv";

config({ path: '.env' });

export const {
    PORT,
    MONGODB_URI_USERS,
    MONGODB_URI_CONTACT,
    JWT_SECRET,
    JWT_EXPIRY,
    JWT_REFRESH_SECRET,
    JWT_REFRESH_EXPIRY,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GITHUB_CALLBACK_URL,
    FRONTEND_URL,
    EMAIL_USER,
    EMAIL_PASSWORD,
    NODE_ENV,
} = process.env;